### ISSUE TITLE
Icon converting error

### ISSUE THREAD

**Issue by Alireza1001** [Axoncodes/XMLtoJSON#7]
I go ahead try converting an SVG icon: `M1346.17,189H153.83C72.74,189,7,255.31,7,337.11v825.78C7,1244.69,72.74,1311,153.83,1311H1346.17c81.09,0,146.83-66.31,146.83-148.11V337.11C1493,255.31,1427.26,189,1346.17,189ZM153.83,1266C97.68,1266,52,1219.74,52,1162.89V337.11C52,280.26,97.68,234,153.83,234H352.5V423H288.13a42.75,42.75,0,0,0-42.63,42.63v34.63a42.76,42.76,0,0,0,42.63,42.63H352.5v56.35H288.13a42.76,42.76,0,0,0-42.63,42.63V676.5a42.75,42.75,0,0,0,42.63,42.63H352.5v56.36H288.13a42.75,42.75,0,0,0-42.63,42.62v34.64a42.75,42.75,0,0,0,42.63,42.62H352.5v56.36H288.13a42.75,42.75,0,0,0-42.63,42.63V1029a42.76,42.76,0,0,0,42.63,42.63H352.5V1266ZM458.37,453A12.79,12.79,0,0,1,471,465.63v34.63a12.79,12.79,0,0,1-12.63,12.63H288.13a12.79,12.79,0,0,1-12.63-12.63V465.63A12.79,12.79,0,0,1,288.13,453Zm0,176.24A12.79,12.79,0,0,1,471,641.87V676.5a12.79,12.79,0,0,1-12.63,12.63H288.13A12.79,12.79,0,0,1,275.5,676.5V641.87a12.79,12.79,0,0,1,12.63-12.63Zm0,176.25A12.79,12.79,0,0,1,471,818.11v34.64a12.79,12.79,0,0,1-12.63,12.62H288.13a12.79,12.79,0,0,1-12.63-12.62V818.11a12.79,12.79,0,0,1,12.63-12.62Zm0,176.24A12.79,12.79,0,0,1,471,994.36V1029a12.79,12.79,0,0,1-12.63,12.63H288.13A12.79,12.79,0,0,1,275.5,1029V994.36a12.79,12.79,0,0,1,12.63-12.63ZM397.5,1266V1071.62h60.87A42.76,42.76,0,0,0,501,1029V994.36a42.75,42.75,0,0,0-42.63-42.63H397.5V895.37h60.87A42.75,42.75,0,0,0,501,852.75V818.11a42.75,42.75,0,0,0-42.63-42.62H397.5V719.13h60.87A42.75,42.75,0,0,0,501,676.5V641.87a42.76,42.76,0,0,0-42.63-42.63H397.5V542.89h60.87A42.76,42.76,0,0,0,501,500.26V465.63A42.75,42.75,0,0,0,458.37,423H397.5V234h330V423H665.13a42.75,42.75,0,0,0-42.63,42.63v34.63a42.76,42.76,0,0,0,42.63,42.63H727.5v56.35H665.13a42.76,42.76,0,0,0-42.63,42.63V676.5a42.75,42.75,0,0,0,42.63,42.63H727.5v232.6H665.13a42.75,42.75,0,0,0-42.63,42.63V1029a42.76,42.76,0,0,0,42.63,42.63H727.5V1266ZM835.37,453A12.79,12.79,0,0,1,848,465.63v34.63a12.79,12.79,0,0,1-12.63,12.63H665.13a12.79,12.79,0,0,1-12.63-12.63V465.63A12.79,12.79,0,0,1,665.13,453Zm0,176.24A12.79,12.79,0,0,1,848,641.87V676.5a12.79,12.79,0,0,1-12.63,12.63H665.13A12.79,12.79,0,0,1,652.5,676.5V641.87a12.79,12.79,0,0,1,12.63-12.63Zm0,352.49A12.79,12.79,0,0,1,848,994.36V1029a12.79,12.79,0,0,1-12.63,12.63H665.13A12.79,12.79,0,0,1,652.5,1029V994.36a12.79,12.79,0,0,1,12.63-12.63ZM772.5,1266V1071.62h62.87A42.76,42.76,0,0,0,878,1029V994.36a42.75,42.75,0,0,0-42.63-42.63H772.5V719.13h62.87A42.75,42.75,0,0,0,878,676.5V641.87a42.76,42.76,0,0,0-42.63-42.63H772.5V542.89h62.87A42.76,42.76,0,0,0,878,500.26V465.63A42.75,42.75,0,0,0,835.37,423H772.5V234h330V775.49h-62.37a42.75,42.75,0,0,0-42.63,42.62v34.64a42.75,42.75,0,0,0,42.63,42.62h62.37v56.36h-62.37a42.75,42.75,0,0,0-42.63,42.63V1029a42.76,42.76,0,0,0,42.63,42.63h62.37V1266Zm437.87-460.51A12.79,12.79,0,0,1,1223,818.11v34.64a12.79,12.79,0,0,1-12.63,12.62H1040.13a12.79,12.79,0,0,1-12.63-12.62V818.11a12.79,12.79,0,0,1,12.63-12.62Zm0,176.24A12.79,12.79,0,0,1,1223,994.36V1029a12.79,12.79,0,0,1-12.63,12.63H1040.13A12.79,12.79,0,0,1,1027.5,1029V994.36a12.79,12.79,0,0,1,12.63-12.63ZM1448,1162.89c0,56.85-45.68,103.11-101.83,103.11H1147.5V1071.62h62.87A42.76,42.76,0,0,0,1253,1029V994.36a42.75,42.75,0,0,0-42.63-42.63H1147.5V895.37h62.87A42.75,42.75,0,0,0,1253,852.75V818.11a42.75,42.75,0,0,0-42.63-42.62H1147.5V234h198.67c56.15,0,101.83,46.26,101.83,103.11Z`

And I get this:
`M 1346.17 1311 H 153.83 C 72.74 1311 7 1244.69 7 1162.89 V 337.11 C 7 255.31 72.74 189 153.83 189 H 1346.17 C 1427.26 189 1493 255.31 1493 337.11 V 1162.89 C 1493 1244.69 1427.26 1311 1346.17 1311 Z M 153.83 234 C 97.68 234 52 280.26 52 337.11 V 1162.89 C 52 1219.74 97.68 1266 153.83 1266 H 352.50 V 1077 H 288.13 A 42.75 42.75 0 0 1 245.50 1034.37 V 999.74 A 42.76 42.76 0 0 1 288.13 957.11 H 352.50 V 900.76 H 288.13 A 42.76 42.76 0 0 1 245.50 858.13 V 823.50 A 42.75 42.75 0 0 1 288.13 780.87 H 352.50 V 724.51 H 288.13 A 42.75 42.75 0 0 1 245.50 681.89 V 647.25 A 42.75 42.75 0 0 1 288.13 604.63 H 352.50 V 548.27 H 288.13 A 42.75 42.75 0 0 1 245.50 505.64 V 471 A 42.76 42.76 0 0 1 288.13 428.37 H 352.50 V 234 Z M 458.37 1047 A 12.79 12.79 0 0 0 471 1034.37 V 999.74 A 12.79 12.79 0 0 0 458.37 987.11 H 288.13 A 12.79 12.79 0 0 0 275.50 999.74 V 1034.37 A 12.79 12.79 0 0 0 288.13 1047 Z M 288.13 870.76 A 12.79 12.79 0 0 0 471 858.13 V 823.50 A 12.79 12.79 0 0 0 458.37 810.87 H 288.13 A 12.79 12.79 0 0 0 275.50 823.50 V 858.13 A 12.79 12.79 0 0 0 288.13 870.76 Z M 288.13 694.51 A 12.79 12.79 0 0 0 471 681.89 V 647.25 A 12.79 12.79 0 0 0 458.37 634.63 H 288.13 A 12.79 12.79 0 0 0 275.50 647.25 V 681.89 A 12.79 12.79 0 0 0 288.13 694.51 Z M 288.13 518.27 A 12.79 12.79 0 0 0 471 505.64 V 471 A 12.79 12.79 0 0 0 458.37 458.37 H 288.13 A 12.79 12.79 0 0 0 275.50 471 V 505.64 A 12.79 12.79 0 0 0 288.13 518.27 Z M 397.50 234 V 428.38 H 458.37 A 42.76 42.76 0 0 1 501 471 V 505.64 A 42.75 42.75 0 0 1 458.37 548.27 H 397.50 V 604.63 H 458.37 A 42.75 42.75 0 0 1 501 647.25 V 681.89 A 42.75 42.75 0 0 1 458.37 724.51 H 397.50 V 780.87 H 458.37 A 42.75 42.75 0 0 1 501 823.50 V 858.13 A 42.76 42.76 0 0 1 458.37 900.76 H 397.50 V 957.11 H 458.37 A 42.76 42.76 0 0 1 501 999.74 V 1034.37 A 42.75 42.75 0 0 1 458.37 1077 H 397.50 V 1266 H 727.50 V 1077 H 665.13 A 42.75 42.75 0 0 1 622.50 1034.37 V 999.74 A 42.76 42.76 0 0 1 665.13 957.11 H 727.50 V 900.76 H 665.13 A 42.76 42.76 0 0 1 622.50 858.13 V 823.50 A 42.75 42.75 0 0 1 665.13 780.87 H 727.50 V 548.27 H 665.13 A 42.75 42.75 0 0 1 622.50 505.64 V 471 A 42.76 42.76 0 0 1 665.13 428.37 H 727.50 V 234 Z M 835.37 1047 A 12.79 12.79 0 0 0 848 1034.37 V 999.74 A 12.79 12.79 0 0 0 835.37 987.11 H 665.13 A 12.79 12.79 0 0 0 652.50 999.74 V 1034.37 A 12.79 12.79 0 0 0 665.13 1047 Z M 665.13 870.76 A 12.79 12.79 0 0 0 848 858.13 V 823.50 A 12.79 12.79 0 0 0 835.37 810.87 H 665.13 A 12.79 12.79 0 0 0 652.50 823.50 V 858.13 A 12.79 12.79 0 0 0 665.13 870.76 Z M 665.13 518.27 A 12.79 12.79 0 0 0 848 505.64 V 471 A 12.79 12.79 0 0 0 835.37 458.37 H 665.13 A 12.79 12.79 0 0 0 652.50 471 V 505.64 A 12.79 12.79 0 0 0 665.13 518.27 Z M 772.50 234 V 428.38 H 835.37 A 42.76 42.76 0 0 1 878 471 V 505.64 A 42.75 42.75 0 0 1 835.37 548.27 H 772.50 V 780.87 H 835.37 A 42.75 42.75 0 0 1 878 823.50 V 858.13 A 42.76 42.76 0 0 1 835.37 900.76 H 772.50 V 957.11 H 835.37 A 42.76 42.76 0 0 1 878 999.74 V 1034.37 A 42.75 42.75 0 0 1 835.37 1077 H 772.50 V 1266 H 1102.50 V 724.51 H 1040.13 A 42.75 42.75 0 0 1 997.50 681.89 V 647.25 A 42.75 42.75 0 0 1 1040.13 604.63 H 1102.50 V 548.27 H 1040.13 A 42.75 42.75 0 0 1 997.50 505.64 V 471 A 42.76 42.76 0 0 1 1040.13 428.37 H 1102.50 V 234 Z M 1540.37 694.51 A 12.79 12.79 0 0 0 1223 681.89 V 647.25 A 12.79 12.79 0 0 0 1210.37 634.63 H 1040.13 A 12.79 12.79 0 0 0 1027.50 647.25 V 681.89 A 12.79 12.79 0 0 0 1040.13 694.51 Z M 1040.13 518.27 A 12.79 12.79 0 0 0 1223 505.64 V 471 A 12.79 12.79 0 0 0 1210.37 458.37 H 1040.13 A 12.79 12.79 0 0 0 1027.50 471 V 505.64 A 12.79 12.79 0 0 0 1040.13 518.27 Z M 1448 337.11 C 1448 280.26 1402.32 234 1346.17 234 H 1147.50 V 428.38 H 1210.37 A 42.76 42.76 0 0 1 1253 471 V 505.64 A 42.75 42.75 0 0 1 1210.37 548.27 H 1147.50 V 604.63 H 1210.37 A 42.75 42.75 0 0 1 1253 647.25 V 681.89 A 42.75 42.75 0 0 1 1210.37 724.51 H 1147.50 V 1266 H 1346.17 C 1402.32 1266 1448 1219.74 1448 1162.89 Z`

**Comment by Rexfont** [comment]
Hello Alireza, thanks for your attention and care, your tickets help us improving our  services, and the issue has been solved in the version 2.1.0 of svgjson
